export const PLAN_OVERVIEW_ACTION_TYPES = {
    FETCH_PLAN_OVERVIEW_START: "FETCH_PLAN_OVERVIEW_START",
    FETCH_PLAN_OVERVIEW_SUCCESS: "FETCH_PLAN_OVERVIEW_SUCCESS",
    FETCH_PLAN_OVERVIEW_FAILURE: "FETCH_PLAN_OVERVIEW_FAILURE",
    FETCH_PLAN_OVERVIEW_STOP: "FETCH_PLAN_OVERVIEW_STOP",
    FETCH_PLAN_OVERVIEW_CLEAR: "FETCH_PLAN_OVERVIEW_CLEAR",
};